### ISSUE TITLE
Values printing

### ISSUE THREAD

**Issue by mbaldinazzo** [sandeeplearner/SO-Code#1]
Here I am.
Everything works great but I have a problem. In my tableview I have 4 section with 10 cells, now when I drag down or drag up it prints n times:
"cell at indexpath nil tapped with switch false"
 and when I tap on the switch it prints:
"cell at indexpath Optional(0) tapped with switch true".

Now I'd like to populate a dictionary [String: String] with index -> the section where I selected and with value -> the indexPath.row of the cell where I touch.

Can you update this github project with this changes? you will save my day :)

**Comment by sandeeplearner** [comment]
Thats because you have impelemented setSelected method of cell :) I wanted to tell you upfront that, it was a wrong approach :) But then thought you are aware of the issue :)

What you can do :)
1. Comment the method setSelected :)
2. Now the only way user can turn on or turn off the switch is by tapping the switch itself (tapping the cell wont do anything)
3. If you want the switch to change its value when user taps the cell implement didSelectRowAtIndexPath  toggle the switch value :) Because you have already written a IBAction for switch on changing its value IBAction will be trigerred and the code inside it will execute and tell you the new value of switch and the cell index :)

Bingo :)

Have a look at the updated code :)

**Comment by mbaldinazzo** [comment]
Ok I'll try now :) Thanks

**Comment by sandeeplearner** [comment]
OK One small mistake :) Please take update now

**Comment by mbaldinazzo** [comment]
@sandeeplearner Updated

**Comment by sandeeplearner** [comment]
Thank u buddy :)
