### ISSUE TITLE
Selection change on drag up/down

### ISSUE THREAD

**Issue by mbaldinazzo** [sandeeplearner/SO-Code#2]
.

**Comment by sandeeplearner** [comment]
You will have to hold the reference of indexPath which is selected buy :) and in cell for rowAtIndexPath check if current indexpath is selected or not if yes simply set cell.mySwitch.setOn(true, animated: true) donbt use the toggleSwitch method it will trigger your delegates thats not intended isnt it :) and if currentIndexPath is not there set the cell.mySwitch.setOn(false, animated: true) :) Simple :)

**Comment by mbaldinazzo** [comment]
@sandeeplearner Thanks you, I tried but nothing change, I have the same effect :( Can you update your code please?

**Comment by sandeeplearner** [comment]
I have updated the code download and have a look :)

I am using an array to maintain the indexpath of selected cells (may it bethrough cell selection or by tapping switch) and when the cell tapped again I remove it :) In cellForRowAtIndexPath am checking if the indexpath exists in array then I turn the switch on else I'll turn it off :) It is essential because cell gets re used in tableView :)

**Comment by mbaldinazzo** [comment]
Thanks man, I tried and it works great:) Really thanks you:)

**Comment by mbaldinazzo** [comment]
So if now I want to found enabled switch that I have previosly selected I have to check the NSIndexPath array in the viewDidLoad I suppose :)
